version: '3.8'

services:
  web-app:
    build: .
    container_name: ecom-trading-app
    depends_on:
      - db
    ports:
      - 443:5000

  db:
    image: mongo:7.0-rc-jammy
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./db:/data/db
    
  # # If Mongo compass is required for debugging, uncomment this service
  # mongo-express:
  #   image: mongo-express
  # container_name: mongo-ui
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
  #     - ME_CONFIG_MONGODB_URL=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@db:27017